### ISSUE TITLE
[Question] - about dev mode

### ISSUE THREAD

**Issue by zgid123** [originjs/vite-plugin-federation#112]
This is not really an issue or something like that.

I just wanna help to build a dev mode. But I still not know how to do it and get lost while trying to research webpack module federation.

If can, can you provide me a vision about this feature of this project and some docs to research?

I will research and help to build the dev mode because this feature will be useful

**Comment by ruleeeer** [comment]
I think if you want to contribute this part first need to understand the implementation principle of federation, you can refer to some blogs or articles (of course the source code of webpack can also be, but I think webpack is too difficult to understand), of course you can also directly check the code of this project, compared to webpack may be easier to read, my documentation related to may not be suitable for you. Because all I was reading was in Chinese.
At this point you need to understand the APIs of the different build tools, because this project is using vite, all we need to do is understand how federation works and reproduce this part on vite
Then you can try to complete the dev part, but there may be some limitations here, because vite is a no bundled build tool, which means you can't create a chunk in dev mode, (which means you can modify part of the generated code, but you can't recreate it, on the remote side we have to create a remoteEntry.js) This is the reason why dev mode is not currently implemented in remote, at this stage dev mode is implemented on the host side, but dev mode for remote may have to wait for vite to open part of the API before it is possible.
Of course, this is just my conclusion, it's been a long time since I last worked on this, maybe some things have changed, maybe you can find some features that I didn't find to accomplish this feature
Thanks for your contribution and effort!

**Comment by zgid123** [comment]
we already have discussion, so this one can be closed, we can discuss inside Discussions later
