### ISSUE TITLE
在remote中使用vuex正常，但是把组件expose到 host中使用时有问题

### ISSUE THREAD

**Issue by jzfai** [originjs/vite-plugin-federation#139]
![image](https://user-images.githubusercontent.com/35098590/156720471-0de28b01-b42e-4c97-8724-ce8574c1eee4.png)

remote
federation({
  name: 'router-remote',
  filename: 'remoteEntry.js',
  exposes: {
    './TestButton': './src/federation/TestButton.vue',
    './Parent': './src/views/example/parent-children/Parent.vue',
    './VuexUse': './src/views/example/vuex-use/VuexUse.vue',
    './test': './src/store/modules/test.ts'
  },
  shared: ['vue','vuex']
}),

host
federation({
  name: "router-host",
  filename: "remoteEntry.js",
  remotes: {
    "router-remote": "http://localhost:5003/vue3-admin-ts/assets/remoteEntry.js",
  },
  shared: ["vue","vuex"]
}),

是不是 remote无法导出vuex到  host中使用，或者有什么出来办法能处理呢

**Comment by ruleeeer** [comment]
Is it possible that the remote side was started using dev mode? Dev mode only supports host side, remote side must use serve mode to run

**Comment by ruleeeer** [comment]
> Is it possible that the remote side was started using dev mode? Dev mode only supports host side, remote side must use serve mode to run

If this is not the cause, a repository may need to be provided to help me locate the problem

**Comment by jzfai** [comment]
1. git clone https://github.com/jzfai/micro-frontend-template.git
2. pnpm i 

you can run separately 
pnpm run  host:preview 
pnpm run  remote:preview

to click this to test
![image](https://user-images.githubusercontent.com/35098590/156910565-acd1b64d-c260-4086-bff1-d47f021c48c2.png)

**Comment by ruleeeer** [comment]
<img width="1085" alt="image" src="https://user-images.githubusercontent.com/70385062/156981940-4062bef4-378a-491a-9392-eae15e1cb9b1.png">
Your cors policy does not allow logins.


But I modified some of the source code to allow me to log in and run (just hoping to give me an out-of-the-box test case), and I reproduced your problem, sorry I've never used vuex, so I had to look at the vuex source code to find that vuex is bound to the vue app instance,Its implementation is probably here:https://github.com/vuejs/vuex/blob/main/src/store.js#L78
``` javascript
install (app, injectKey) {
    app.provide(injectKey || storeKey, this)
    app.config.globalProperties.$store = this

    const useDevtools = this._devtools !== undefined
      ? this._devtools
      : __DEV__ || __VUE_PROD_DEVTOOLS__

    if (useDevtools) {
      addDevtools(app, this)
    }
  }
``` 

Since host and remote are running on different vue app instances, when you use remote components, you can only use the store information that has been registered on the host side

There are two possible solutions for this: 
1. define a mutation `test.js` in the host side
2. refer to [this practice](https://github.com/originjs/vite-plugin-federation/blob/main/packages/examples/vue3-advanced-demo/router-remote/src/components/ShoppingCart.vue#L32) to re-register once
