### ISSUE TITLE
there are  error in microsoft edge  and 360 browser, wx browser  but  is normal in chrome and firefox

### ISSUE THREAD

**Issue by jzfai** [originjs/vite-plugin-federation#140]
![image](https://user-images.githubusercontent.com/35098590/156910795-0cfb7c5f-8373-408f-9b07-e71f0d85aed1.png)

you can visit    http://8.135.1.141/micro-frontend-template    to test 

or 

git clone https://github.com/jzfai/micro-frontend-template.git
pnpm i
pnpm run hostall:preview-offline
and then using http://localhost:5012/micro-frontend-template/  to test

**Comment by ruleeeer** [comment]
This should be because `vite-plugin-federation` uses relatively new features (such as top-level-await), which is only implemented in some newer browsers, but excluding this part, Vue3 does not support IE, as far as I know, the old Microsoft Edge browser (I see your screenshot this should be the old version of EDGE) is using the IE kernel, and 360 browser in extreme mode is using the Chromium kernel, and in compatibility mode is using the IE kernel, I guess the error should be running in compatibility mode

**Comment by jzfai** [comment]
but is normal when i visit the vue3 project , using in vue:3.2.31
![image](https://user-images.githubusercontent.com/35098590/157187127-66d16a81-9c60-4dd7-8800-2fb5ea4962d0.png)
you can visit http://8.135.1.141/vue3-admin-plus/     to test

**Comment by ruleeeer** [comment]
I have no plans to support older versions of EDGE (because maintenance has been abandoned)

**Comment by jzfai** [comment]
ok， thanks for you answer
