### ISSUE TITLE
vite.config.ts同时配置remotes和exposes就会报错远程模块找不到。

### ISSUE THREAD

**Issue by SanMako** [originjs/vite-plugin-federation#222]
### Versions

- originjs: V ^1.1.7
- node:  v14.17.3
- vue : ^3.2.37

这是我的配置：如果去掉expose，可以正常加载远程模块
![image](https://user-images.githubusercontent.com/76836628/180944279-8e2819b2-22fe-496e-8f7e-c6143a16d1be.png)

加上expose，就会报错，如下图：
![image](https://user-images.githubusercontent.com/76836628/180944815-3767864d-42d8-43ec-bcde-f38734d516c1.png)

### What is Expected?
如果可以加载其他模块，加工之后在导出模块供其他使用就好了。我尝试webpack5的是可以的。

**Comment by flyfishzy** [comment]
请提供一个复现工程。
Please provide a reproduction project.

**Comment by IsmaOrdas** [comment]
I'm having the same problem. Can't "expose" and "remote" at the same time in a vite config file in my host app. If I delete the "exposes" block, the import works fine again.

**Comment by SanMako** [comment]
@flyfishzy 这是我的demo工程，辛苦大佬了，谢谢。
[vite-mf-test.zip](https://github.com/originjs/vite-plugin-federation/files/9205304/vite-mf-test.zip)

**Comment by SanMako** [comment]
> 请提供一个复现工程。 Please provide a reproduction project.

@flyfishzy 这是我的demo工程，辛苦大佬了，谢谢。
[vite-mf-test.zip](https://github.com/originjs/vite-plugin-federation/files/9205321/vite-mf-test.zip)

**Comment by flyfishzy** [comment]
Add a `declare module "router-remote/*"{}` in your .d.ts file.
Duplicate of https://github.com/originjs/vite-plugin-federation/issues/129.
Maybe we need a typescript example project.

**Comment by SanMako** [comment]
> declare module "router-remote/*"{}

大佬，你可能没明白我的问题，我说的不是编译报错，而是加载组件会报错找不到。

**Comment by SanMako** [comment]
> declare module "router-remote/*"{}

大佬，你可能没明白我的问题，我说的不是编译报错，而是加载组件会报错找不到。

**Comment by ruleeeer** [comment]
我尝试更改一下你的项目，这里是git diff的截图
I would try to change your project, here is a screenshot of git diff

![图片](https://user-images.githubusercontent.com/70385062/182521391-10dbbf1b-d543-447d-909c-3f5edc37fbec.png)

在我这里是可以成功编译和运行的
It compiles and runs successfully in my case

![图片](https://user-images.githubusercontent.com/70385062/182521649-c8b15129-1b5f-438c-b7b6-23d29f42042d.png)

我猜测你使用了dev模式启动了其中的项目，在你的项目里只能使用build&preview模式启动，因为只有完全的host端才可以使用dev模式启动（app-one和app-two都包含了exposes，只包含remotes配置的才可以使用dev）
I guess you used dev mode to start one of the projects, you can only use build&preview mode to start in your project, because only the full host side can use dev mode to start (app-one and app-two both contain exposes, only those containing remotes configuration can use dev)

**Comment by SanMako** [comment]
> 

好的，我明白了。谢谢。

**Comment by iotopo** [comment]
同时包含了 exposes 和 remotes 的项目，为什么不能支持 dev 模式呢？

**Comment by ruleeeer** [comment]
由于vite的开发模式不能在运行时手动生成新的块，这导致远程不能生成remoteEntryjs文件。

Because vite's dev mode cannot manually generate new chunks during runtime, this causes remote to not generate remoteEntryjs files
