### ISSUE TITLE
problem to expose remote entry when use vite

### ISSUE THREAD

**Issue by misaku** [originjs/vite-plugin-federation#241]
### Versions

- vite-plugin-federation:  v1.1.9
- vite: v3.0.7

### Reproduction

<details open>
<summary>Additional Details</summary>
<br>

```TS
/// <reference types="vitest" />
import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import federation from '@originjs/vite-plugin-federation';

export default defineConfig({
  plugins: [
    react(),
    federation({
      name: 'core',
      filename: 'remoteEntry.js',
      exposes: {
        './Sidebar':'./src/Sidebar'
      },
      remotes: {
        foo: 'remote_foo',
      },
      shared: ['react'],
    }),
  ],
  test: {
    globals: true,
    environment: 'happy-dom',
  },
});
```

</details>

### Steps to reproduce
 - install plugin
 - start with deve or preview  and try to access routes
    ```
    http://localhost:[PORT]/remoteEntry.js
    ```
### What is Expected?
expose files
### What is actually happening?
404 not found

**Comment by ruleeeer** [comment]
If you are using `vite` and have not made any special adjustments, usually the `remoteEntry` file is accessed at http://localhost:[port]/assets/remoteEntry.js instead of http://localhost:[port]/remoteEntry.js , here are [some examples](https://github.com/originjs/vite-plugin-federation/tree/main/packages/examples) to help you quick start
